version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: nyaysphere-postgres
    environment:
      POSTGRES_DB: nyaysphere
      POSTGRES_USER: nyaysphere
      POSTGRES_PASSWORD: nyaysphere123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nyaysphere"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MinIO Object Storage
  minio:
    image: minio/minio:latest
    container_name: nyaysphere-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Backend API
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: nyaysphere-backend
    environment:
      DATABASE_URL: postgresql://nyaysphere:nyaysphere123@postgres:5432/nyaysphere
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      STORAGE_ENDPOINT: http://minio:9000
      STORAGE_ACCESS_KEY: minioadmin
      STORAGE_SECRET_KEY: minioadmin123
      STORAGE_BUCKET: nyaysphere-documents
      STORAGE_REGION: us-east-1
      PORT: 3001
      NODE_ENV: production
      FRONTEND_URL: http://localhost:5173
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npx prisma generate &&
        npm run db:seed &&
        npm start
      "

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: nyaysphere-frontend
    environment:
      VITE_API_URL: http://localhost:3001
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
  minio_data:

networks:
  default:
    name: nyaysphere-network
